# Generated by Django 4.2.8 on 2023-12-11 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAnalisis', models.DateField()),
                ('infoUsuario', models.CharField(max_length=80)),
                ('resultadosAlmacenados', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='medidorDeConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumoTotal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='registroDispositivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumoKwh', models.FloatField()),
                ('tiempoDeUso', models.DateField()),
                ('cantidadDispositivos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=90)),
                ('cedula', models.CharField(max_length=50)),
            ],
        ),
    ]
