# Generated by Django 4.2.8 on 2023-12-11 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='apellido',
            new_name='_apellido',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='cedula',
            new_name='_cedula',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='direccion',
            new_name='_direccion',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre',
            new_name='_nombre',
        ),
        migrations.AddField(
            model_name='informe',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prestamoList', to='consumo.usuario'),
            preserve_default=False,
        ),
    ]
